### PR TITLE
namelist 'field_manipulator'

### PR DESCRIPTION
**Pull request by ZeugAusHH**
Adds 'field_manipulator' namelist.

Currently only scaling of power of the light field is supported, but I plan to implement some additional features in the future.

Example:
```
&field_manipulator
   harm = 1
   scale_power = 0.1
&end
```
==> Power of field in fundamental is attenuated by one order of magnitude. By putting multiple of these blocks, different harmonics can be scaled by different factors (for instance for harmonic lasing studies).

The manipulation is done in memory, avoiding time-intensive file-based field manipulation, which uses the steps: (i) dumping of fields to files, (ii) manipulation of the files, and (iii) loading fields into GENESIS again to continue with the simulation.

During the merge, CHANGELOG.md will generate a conflict that has to be manually resolved (order of the text blocks).

### CODE REVIEW

**Comment by svenreiche** [comment]
Cannot make the command line merge since I do not have the access right to ZeusAusHH/Genesis-1.3-Version4.git

**Comment by ZeugAusHH** [comment]
Dear Sven,

thank you for your message.

I assume that the program is complaining about missing write permissions, but I would not expect that permissions of my repository should prevent this operation (as it is the source repository for the merge operation).

Are you sure that you are on the correct branch while merging? In case that this is really an issue, I will of course adjust the permissions accordingly.

Best
Christoph

**Comment by svenreiche** [comment]
Hi Christoph,
it worked when using https. Still I merged and I do not see any difference. Still working on it

**Comment by svenreiche** [comment]
Ok, I figured it out. Was not quite the command line they suggested here. Branches are merged now.

**Pull request merged**
